### PR TITLE
core: Add fs-basename function

### PR DESCRIPTION
**Pull request by danielbayley**
~~~ yaml
# ~/path/to/file.ys
filename:: fs-basename(FILE) # file.ys
basename:: fs-basename(FILE "ys") # file
~~~

### CODE REVIEW

**Comment by ingydotnet** [comment]
Hi. Thanks for trying out YS and thanks for the PR.
Love collaboration!

I'm not entirely opposed to this, but these already work:

```
$ ys -pe "fs-filename('$PWD/ReadMe.md')"
"ReadMe.md"
$ ys -pe "fs-filename('$PWD/ReadMe.md').replace('.md')"
"ReadMe"
```

Tell me a bit why you'd prefer this if you don't mind.

**Comment by ingydotnet** [comment]
@danielbayley I added a couple commits to your work here https://github.com/yaml/yamlscript/tree/fs-basename

Let me know what you think.

**Comment by danielbayley** [comment]
> Tell me a bit why you'd prefer this if you don't mind.

@ingydotnet Sure, so I was going on the Ruby [`basename`](https://apidock.com/ruby/File/basename/class) method, which has an optional second param to remove the given extension, or more usefully, has the ability to remove _any_ extension with a basic glob:
~~~ yaml
# ~/path/to/file.ys
fs-basename(FILE ".*") # file
~~~

> these already work:
> ~~~
> $ ys -pe "fs-filename('$PWD/ReadMe.md').replace('.md')"
> "ReadMe"
> ~~~

As does this:
~~~ yaml
fs-filename(FILE):fs/strip-ext
~~~
But it’s still 2 methods, rather than one. If I’m going to mix code directly into my data, I want it to be a terse as possible (without losing legibility).

Also on that note, how come [`fs/strip-ext`](https://github.com/babashka/fs/blob/master/API.md#babashka.fs/strip-ext), and [`fs/split-ext`](https://github.com/babashka/fs/blob/master/API.md#babashka.fs/split-ext) are not aliased to `fs-stripext`/`fs-splitext` respectively, and included with the other `fs-*` methods, as listed [here](https://github.com/yaml/yamlscript/blob/main/doc/ys-std.md#file-system-functions)?

I also thought about adding this second param to the existing `fs-filename` method, and/or just having `fs-basename` as a straight up alias to that…

What do you think? @ingydotnet

Further reading on this: https://github.com/babashka/fs/issues/28, and https://github.com/babashka/fs/pull/29.

**Comment by ingydotnet** [comment]
> If I’m going to mix code directly into my data, I want it to be as terse as possible (without losing legibility).

We have shared goals there!!

I'll look it all over in a bit and push some commits for you to review

**Comment by ingydotnet** [comment]
We don't need to alias `fs/split-ext` because we can just use that directly, no?
```
$ ys -pe "fs-filename('$PWD/ReadMe.md'):fs/split-ext"
["ReadMe" "md"]
```

**Comment by ingydotnet** [comment]
I'll add support for 
```
fs-basename(FILE '*')
```
note that `fs/strip-ext` doesn't use a `.` in the ext.

**Comment by danielbayley** [comment]
> We don't need to alias `fs/split-ext` because we can just use that directly, no?

Well yes, but then why alias some and not others? I’m just thinking about consistency is all…

**Comment by ingydotnet** [comment]
> > We don't need to alias `fs/split-ext` because we can just use that directly, no?
> 
> Well yes, but then why alias some and not others? I’m just thinking about consistency is all…

afaict, none of `std/fs-foobar` match `fs/foobar` exactly. 

Some are close like `fs-filename` because I prefer `filename` to `file-name`.

**Comment by ingydotnet** [comment]
Pushed 14a53e62 to `devel` branch.

**Comment by ingydotnet** [comment]
This was refactored and released in 0.1.87.

**Comment by ingydotnet** [comment]
Closing.

**Pull request closed without merging**
