### PR TITLE
core: Fix GitHub syntax highlighting

### PR DESCRIPTION
**Pull request by danielbayley**
Force GitHub to highlight `*.ys` files as YAML.

### CODE REVIEW

**Comment by ingydotnet** [comment]
Awesome. I didn't know about this. 

I can apply this for now but we should possibly look at other syntaxes.

Weirdly, highlighting as powershell works pretty good in vscode...

**Comment by danielbayley** [comment]
> we should possibly look at other syntaxes.

Ideally, a `YAMLScript:` entry would be added to _[linguist](https://github.com/github-linguist/linguist#readme)_ [here](https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml#L8309), the library responsible for syntax highlighting on here… But I think they have minimum constraints around popularity/usage, so the project will probably need to grow a lot more before they would accept a PR…

> Weirdly, highlighting as powershell works pretty good in vscode...

PowerShell is also [listed](https://github.com/github-linguist/linguist/blob/main/lib/linguist/languages.yml#L5570), so you could change this to the following, if that would render better highlighting…
~~~ gitattributes
*.ys linguist-language=powershell
~~~

**Comment by ingydotnet** [comment]
do you know if `*.ys` applies to code sections like
````
```ys
!yamlscript/v0
say: 42
```
````

**Comment by danielbayley** [comment]
> do you know if `*.ys` applies to code sections like
> 
> ~~~
> ```ys
> !yamlscript/v0
> say: 42
> ```
> ~~~

I _think_ that would only work after a merged PR entry to linguist… Until then, would have to just do:
~~~ md
``` yaml
!yamlscript/v0
say: 42
```
~~~
or
``` md
~~~ yaml
!yamlscript/v0
say: 42
~~~
````

**Comment by ingydotnet** [comment]
I can certainly test it out on a branch,,,

**Comment by ingydotnet** [comment]
I realized that I can retarget the PR myself.
Retargeted to devel.

**Comment by ingydotnet** [comment]
@danielbayley do you have any experience creating a new syntax highlighter for linguist?

**Comment by ingydotnet** [comment]
Merged into a branch intended for 0.1.88

**Comment by ingydotnet** [comment]
YAML syntax highlighting is fine for now, but I'd like to get real ys token highlighting.

**Comment by danielbayley** [comment]
> @danielbayley do you have any experience creating a new syntax highlighter for linguist?

@ingydotnet Iv'e done plenty of parsing stuff, but not really much in the context of syntax highlighting—apart from minor related things in _[Atom](https://atom.io)_ packages… I imagine Linguist probably uses something like _TextMate grammars_, or something RegEx-based.

> I'd like to get real ys token highlighting.

Yeah ideally! I will say for sure, the much better approach would be the _[Tree-sitter](https://tree-sitter.github.io/tree-sitter)_/[AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) route…

**Comment by ingydotnet** [comment]
I've also done a bunch with parsing including creating the Pegex grammar language: https://github.com/pegex-parser
and also a little bit of syntax highlighting for CodeMirror, but not much.

I think the big thing that YS needs first is a language server.`
The YAMLScript compiler is perfectly postured to work as an LSP implementation for YAML and YS.

Here's a visual of the comilper in action:
```
$ ys -cde 'say: 2 + 3'
*** parse     *** 0.211807 ms

({:+ "+MAP", :! "yamlscript/v0/code"}
 {:+ "=VAL", := "say"}
 {:+ "=VAL", := "2 + 3"}
 {:+ "-MAP"}
 {:+ "-DOC"})

*** compose   *** 0.005074 ms

{:! "yamlscript/v0/code", :% [{:= "say"} {:= "2 + 3"}]}

*** resolve   *** 0.042651 ms

{:xmap [{:expr "say"} {:expr "2 + 3"}]}

*** build     *** 0.108232 ms

{:xmap [{:Sym say} {:Lst [{:Sym add+} {:Int 2} {:Int 3}]}]}

*** transform *** 0.027301 ms

{:xmap [{:Sym say} {:Lst [{:Sym add+} {:Int 2} {:Int 3}]}]}

*** construct *** 0.051574 ms

{:Top [{:Lst [{:Sym say} {:Lst [{:Sym add+} {:Int 2} {:Int 3}]}]}]}

*** print     *** 0.004313 ms

"(say (add+ 2 3))"

(say (add+ 2 3))
```
The output of the **build** stage should have all the info we need, except for input position (line/col).
The parser that YS uses does report that information but it is currently ignored.

**Pull request merged**
